name: Minigame
version: ${project.version}
main: me.ohowe.minigame.Plugin
api-version: "1.16"

commands:
    minigame:
        description: The minigame command

permissions:
    hideseek-seeker:
        default: op
    minigame-start:
        default: op
    minigame-set:
        default: op